apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: m79r5k4w4-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:871cc1cfe543d88834e36e1f794f932cb867c3c6@sha256:54f58072392f2cedadf30a56caa5755f4dfb680f274b095c6acd383cd8a1b3b4
          name: container-image
