apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m79r5k4w4-go
  janus-idp.io/tekton: m79r5k4w4-go
  backstage.io/kubernetes-id: m79r5k4w4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m79r5k4w4-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
